### ISSUE TITLE
Por que aqui você escolheu utilizar a função "dict" em vez do literal "{}"?

### ISSUE THREAD

**Issue by mstrcnvs** [illozzam/acmevita#1]
https://github.com/illozzam/acmevita/blob/68d6095ae15a707d2d2970c2ed4d0cd681b13ed9/test_app.py#L55

**Comment by illozzam** [comment]
Naquele momento, eu estava fazendo uma série de testes nessas funções de testagem e, como queria ser rápido, utilizei a forma mais "prática" (com menos aspas, etc) de expressar a estrutura de um dicionário. Mas normalmente utilizo o literal mesmo.

**Comment by mstrcnvs** [comment]
Boa!
