### ISSUE TITLE
Por que aqui você escolheu não converter a resposta da requisição para um dicionário antes de verificar o assert? Vi que está verificando como bytes

### ISSUE THREAD

**Issue by mstrcnvs** [illozzam/acmevita#2]
https://github.com/illozzam/acmevita/blob/68d6095ae15a707d2d2970c2ed4d0cd681b13ed9/test_app.py#L34

**Comment by illozzam** [comment]
Estou acostumado com as rotinas de testes do Django que, embora parecidas, não são completamente iguais. Então eu me baseei nesse tutorial para fazer os testes automatizados: https://flask.palletsprojects.com/en/1.1.x/testing/ e, nele, é utilizada essa notação.

**Comment by mstrcnvs** [comment]
Entendi. Essa notação é um pouquinho mais difícil de manter e entender do que convertendo a resposta pra um dicionário, mas também funciona e é recomendada!
