### ISSUE TITLE
Já chegou a utilizar o Swagger/OpenAPI para documentação funcional de APIs?

### ISSUE THREAD

**Issue by mstrcnvs** [illozzam/acmevita#3]
https://github.com/illozzam/acmevita/blob/master/README.md

**Comment by illozzam** [comment]
Nunca utilizei essas ferramentas em meus projetos mas vou dar uma pesquisada sobre elas. Obrigado pela informação!

**Comment by mstrcnvs** [comment]
Imagina, é bem legal mesmo!
