### ISSUE TITLE
O que seria esse diretório instance?

### ISSUE THREAD

**Issue by mstrcnvs** [illozzam/acmevita#4]
https://github.com/illozzam/acmevita/blob/68d6095ae15a707d2d2970c2ed4d0cd681b13ed9/app/blueprints/.gitignore#L1

**Comment by illozzam** [comment]
Na linha 9 do __init__.py em app, eu estabeleço que o banco de dados deve ser gravado no diretório da instância da API, no arquivo "acmevita.db". Esse arquivo é gerado quando o usuário executa o comando "app.db.create_all()" e ficará gravado no diretório "instance/", dentro da pasta do projeto. Citei-o no .gitignore apenas para que o meu banco de dados não fosse comitado junto com o código.

**Comment by mstrcnvs** [comment]
Entendi! Tranquilo.
