### ISSUE TITLE
A biblioteca Marshmallow oferece desserialização, que seria, validação de dados de entrada e instanciação dos modelos, por que nesse caso você escolheu não utilizar?

### ISSUE THREAD

**Issue by mstrcnvs** [illozzam/acmevita#5]
https://github.com/illozzam/acmevita/blob/68d6095ae15a707d2d2970c2ed4d0cd681b13ed9/app/blueprints/departments.py#L44

**Comment by illozzam** [comment]
Como foi feito, eu já estou validando os dados na própria função. Como eu não tenho total domínio da biblioteca ainda, optei por fazer de uma forma que eu tenho mais segurança no momento e que sei que funcionaria bem. Mas pretendo, estudando mais a ferramenta, adquirir esse domínio que me falta e utilizar suas estruturas com mais frequência.

**Comment by mstrcnvs** [comment]
Boa!
