### ISSUE TITLE
Percebi que colocou os verbos da ação dos endpoints na própria URL (list, insert). Por que escolheu não utilizar o REST nesse caso?

### ISSUE THREAD

**Issue by mstrcnvs** [illozzam/acmevita#6]
https://github.com/illozzam/acmevita/blob/68d6095ae15a707d2d2970c2ed4d0cd681b13ed9/app/blueprints/departments.py#L31

**Comment by illozzam** [comment]
Em outra situação, fui criticado pelo gestor do projeto por utilizar o modelo REST na API e, por esse motivo, como não tínhamos acordado antes, não o utilizei nesse teste. Mas não tenho nenhum motivo para não usá-lo. Se quiser, posso fazer essa alteração.

**Comment by mstrcnvs** [comment]
Tranquilo, não precisa não! Só pra entender o porque.
